ENROL = "../cpp/Enroll/Enroll.ino"
ACTIVATE = "../cpp/Fingerprint/Fingerprint.ino"
PIN_OUT_TXT = "resources/pinout.txt"
PASSWORD_FILE = "../cpp/Fingerprint/password.h"
PROJECT_CONFIG = "resources/config.txt"